### ISSUE TITLE
Incorrect coding for name of repository

### ISSUE THREAD

**Issue by jayesbe** [odan/base32#3]
The code class is called Base36.

But the function of the class is not Base 36 but Base 32.

Base 36 encoding should be 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'

https://en.wikipedia.org/wiki/Base36#PHP_implementation

**Comment by odan** [comment]
You are right :-) 

I even mentioned this in a comment, but still gave the library a wrong name.

I will therefore rename the library to odan/base32.

Thank you very much!
